title: Finance Dashboard
--logo: /assets/img/headshot_circle.png
--#description: Finance Dashboard for Paper&Ink Co.
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
  show_downloads: false
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
